### ISSUE TITLE
Segmentation fault (core dumped) - Build on Ubuntu 18.04

### ISSUE THREAD

**Issue by ChrisSlS** [xenia-project/xenia#1159]
Hello,

After building [this](https://travis-ci.org/xenia-project/xenia/jobs/382478657), i can't execute xenia : 

```
~/xenia-project/xenia/build/bin/Linux/Release$ ./xenia

(xenia:9516): Gtk-WARNING **: 07:23:52.430: Theme parsing error: gtk-contained.css:24:64: Using one color stop with linear-gradient() is deprecated.

(xenia:9516): Gtk-WARNING **: 07:23:52.430: Theme parsing error: gtk-contained.css:58:64: Using one color stop with linear-gradient() is deprecated.

(xenia:9516): Gtk-WARNING **: 07:23:52.435: Theme parsing error: gtk-contained.css:2527:75: Using one color stop with linear-gradient() is deprecated.

(xenia:9516): Gtk-WARNING **: 07:23:52.435: Theme parsing error: gtk-contained.css:2857:13: Expected a length

(xenia:9516): Gtk-WARNING **: 07:23:52.435: Theme parsing error: gtk-contained.css:2889:37: The :prelight pseudo-class is deprecated. Use :hover instead.

(xenia:9516): Gtk-WARNING **: 07:23:52.436: Theme parsing error: gtk-contained.css:3526:8: Junk at end of value for background-image

(xenia:9516): Gtk-WARNING **: 07:23:52.437: Theme parsing error: gtk-contained.css:4215:73: Using one color stop with linear-gradient() is deprecated.

(xenia:9516): Gtk-WARNING **: 07:23:52.437: Theme parsing error: gtk-contained.css:4227:87: Using one color stop with linear-gradient() is deprecated.
Erreur de segmentation (core dumped)
```
Can you help me please ?

Thank you for your work, it looks promising !

**Comment by ChrisSlS** [comment]
Thanks for your answer.

Here the result : 

`Reading symbols from ./xenia...(no debugging symbols found)...done`

**Comment by mrcmunir** [comment]
@ChrisSIS You missing run ./xenia and not put bt command.

1) gdb ./xenia
Readyn done.
After that 
2) run  
When crash 
3) bt command  for backtrace .

**Comment by ChrisSlS** [comment]
Oh sorry, I never used the debug tool ^^

Voilà :

```
Starting program: /home/jean/xenia-project/xenia/build/bin/Linux/Release/xenia 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec49c700 (LWP 24049)]
[New Thread 0x7fffeb258700 (LWP 24050)]
[New Thread 0x7fffea1bc700 (LWP 24051)]
[New Thread 0x7fffe99bb700 (LWP 24052)]

(xenia:24045): Gtk-WARNING **: 12:03:48.574: Theme parsing error: gtk-contained.css:24:64: Using one color stop with linear-gradient() is deprecated.

(xenia:24045): Gtk-WARNING **: 12:03:48.574: Theme parsing error: gtk-contained.css:58:64: Using one color stop with linear-gradient() is deprecated.

(xenia:24045): Gtk-WARNING **: 12:03:48.578: Theme parsing error: gtk-contained.css:2527:75: Using one color stop with linear-gradient() is deprecated.

(xenia:24045): Gtk-WARNING **: 12:03:48.579: Theme parsing error: gtk-contained.css:2857:13: Expected a length

(xenia:24045): Gtk-WARNING **: 12:03:48.579: Theme parsing error: gtk-contained.css:2889:37: The :prelight pseudo-class is deprecated. Use :hover instead.

(xenia:24045): Gtk-WARNING **: 12:03:48.581: Theme parsing error: gtk-contained.css:3526:8: Junk at end of value for background-image

(xenia:24045): Gtk-WARNING **: 12:03:48.582: Theme parsing error: gtk-contained.css:4215:73: Using one color stop with linear-gradient() is deprecated.

(xenia:24045): Gtk-WARNING **: 12:03:48.582: Theme parsing error: gtk-contained.css:4227:87: Using one color stop with linear-gradient() is deprecated.

Thread 3 "Win32 Loop" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb258700 (LWP 24050)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00000000005d0602 in xe::ui::vulkan::VulkanContext::Initialize() ()
#2  0x00000000005d61c4 in xe::ui::vulkan::VulkanProvider::CreateContext(xe::ui::Window*) ()
#3  0x0000000000523bc3 in std::_Function_handler<void (), xe::gpu::GraphicsSystem::Setup(xe::cpu::Processor*, xe::kernel::KernelState*, xe::ui::Window*)::$_0>::_M_invoke(std::_Any_data const&) ()
#4  0x00000000005c7c81 in std::_Function_handler<void (), xe::ui::Loop::PostSynchronous(std::function<void ()>)::$_0>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000005c7f6b in xe::ui::_posted_fn_thunk(void*) ()
#6  0x00007ffff7204080 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff5b520f5 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff5b524c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff5b527d2 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff76fd385 in gtk_main ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00000000005c81c0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<xe::ui::GTKLoop::GTKLoop()::$_0> > >::_M_run() ()
#12 0x00007ffff3ec256f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff58ee6db in start_thread (arg=0x7fffeb258700)
    at pthread_create.c:463
---Type <return> to continue, or q <return> to quit---
#14 0x00007ffff357f88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ChrisSlS** [comment]
Hello @mrcmunir ,

I have the same problem after updating xenia, except that the error seems a little different this time :

```
Reading symbols from ./xenia...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/jean/xenia-project/xenia/build/bin/Linux/Release/xenia 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec49c700 (LWP 20086)]
[New Thread 0x7fffeb258700 (LWP 20087)]
[New Thread 0x7fffea1bc700 (LWP 20088)]
[New Thread 0x7fffe99bb700 (LWP 20089)]

(xenia:20080): Gtk-WARNING **: 04:49:43.999: Theme parsing error: gtk-contained.css:24:64: Using one color stop with linear-gradient() is deprecated.

(xenia:20080): Gtk-WARNING **: 04:49:43.999: Theme parsing error: gtk-contained.css:58:64: Using one color stop with linear-gradient() is deprecated.

(xenia:20080): Gtk-WARNING **: 04:49:44.003: Theme parsing error: gtk-contained.css:2527:75: Using one color stop with linear-gradient() is deprecated.

(xenia:20080): Gtk-WARNING **: 04:49:44.004: Theme parsing error: gtk-contained.css:2857:13: Expected a length

(xenia:20080): Gtk-WARNING **: 04:49:44.004: Theme parsing error: gtk-contained.css:2889:37: The :prelight pseudo-class is deprecated. Use :hover instead.

(xenia:20080): Gtk-WARNING **: 04:49:44.005: Theme parsing error: gtk-contained.css:3526:8: Junk at end of value for background-image

(xenia:20080): Gtk-WARNING **: 04:49:44.006: Theme parsing error: gtk-contained.css:4215:73: Using one color stop with linear-gradient() is deprecated.

(xenia:20080): Gtk-WARNING **: 04:49:44.006: Theme parsing error: gtk-contained.css:4227:87: Using one color stop with linear-gradient() is deprecated.

Thread 3 "Win32 Loop" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb258700 (LWP 20087)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00000000005d5632 in xe::ui::vulkan::VulkanContext::Initialize() ()
#2  0x00000000005db1f4 in xe::ui::vulkan::VulkanProvider::CreateContext(xe::ui::Window*) ()
#3  0x0000000000524d73 in std::_Function_handler<void (), xe::gpu::GraphicsSystem::Setup(xe::cpu::Processor*, xe::kernel::KernelState*, xe::ui::Window*)::$_0>::_M_invoke(std::_Any_data const&) ()
#4  0x00000000005cccb1 in std::_Function_handler<void (), xe::ui::Loop::PostSynchronous(std::function<void ()>)::$_0>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000005ccf9b in xe::ui::_posted_fn_thunk(void*) ()
#6  0x00007ffff7204080 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff5b520f5 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff5b524c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff5b527d2 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff76fd385 in gtk_main ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00000000005cd1f0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<xe::ui::GTKLoop::GTKLoop()::$_0> > >::_M_run() ()
#12 0x00007ffff3ec256f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff58ee6db in start_thread (arg=0x7fffeb258700)
    at pthread_create.c:463
---Type <return> to continue, or q <return> to quit---
```

**Comment by gibbed** [comment]
Linux is a WIP, and isn't functioning yet.
