### ISSUE TITLE
Linux - xenia-cpu-tests fails (ADD_I8)

### ISSUE THREAD

**Issue by 7oxicshadow** [xenia-project/xenia#1266]
I realise that Linux isn't really a priority at the moment as the progress using a DX12 backed is really benefiting this emulator but just in-case a member of the community is able to assist with the Linux side of things the cpu tests fail on linux.

```
[toxicshadow@PC_1 Debug]$ ./xenia-cpu-tests
xenia-cpu-tests: ../src/xenia/cpu/testing/util.h:76: void xe::cpu::testing::TestFunction::Run(std::function<void (PPCContext *)>, std::function<void (PPCContext *)>): Assertion `false' failed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xenia-cpu-tests is a Catch v1.9.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
ADD_I8
-------------------------------------------------------------------------------
../src/xenia/cpu/testing/add_test.cc:19
...............................................................................

../src/xenia/cpu/testing/add_test.cc:19: FAILED:
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

Aborted (core dumped)
```
**GDB output**

```
(gdb) run
Starting program: /mnt/games/native_emulators/source_files/xenia/build/bin/Linux/Debug/xenia-cpu-tests 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.27-32.fc28.x86_64
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
xenia-cpu-tests: ../src/xenia/cpu/testing/util.h:76: void xe::cpu::testing::TestFunction::Run(std::function<void (PPCContext *)>, std::function<void (PPCContext *)>): Assertion `false' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff40eeeab in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-atk-2.26.2-1.fc28.x86_64 at-spi2-core-2.28.0-1.fc28.x86_64 atk-2.28.1-1.fc28.x86_64 bzip2-libs-1.0.6-26.fc28.x86_64 cairo-1.15.12-2.fc28.x86_64 cairo-gobject-1.15.12-2.fc28.x86_64 dbus-libs-1.12.10-1.fc28.x86_64 expat-2.2.5-3.fc28.x86_64 fontconfig-2.13.0-5.fc28.x86_64 freetype-2.8-10.fc28.x86_64 fribidi-1.0.2-1.fc28.x86_64 gdk-pixbuf2-2.36.12-1.fc28.x86_64 glib2-2.56.3-2.fc28.x86_64 graphite2-1.3.10-5.fc28.x86_64 gtk3-3.22.30-1.fc28.x86_64 harfbuzz-1.7.5-3.fc28.x86_64 libX11-1.6.5-7.fc28.x86_64 libXau-1.0.8-11.fc28.x86_64 libXcomposite-0.4.4-12.fc28.x86_64 libXcursor-1.1.15-1.fc28.x86_64 libXdamage-1.1.4-12.fc28.x86_64 libXext-1.3.3-8.fc28.x86_64 libXfixes-5.0.3-5.fc28.x86_64 libXi-1.7.9-6.fc28.x86_64 libXinerama-1.1.3-10.fc28.x86_64 libXrandr-1.5.1-5.fc28.x86_64 libXrender-0.9.10-5.fc28.x86_64 libblkid-2.32.1-1.fc28.x86_64 libcap-2.25-9.fc28.x86_64 libcxx-6.0.0-2.fc28.x86_64 libcxxabi-6.0.0-2.fc28.x86_64 libdatrie-0.2.9-7.fc28.x86_64 libepoxy-1.5.2-1.fc28.x86_64 libffi-3.1-16.fc28.x86_64 libgcc-8.2.1-5.fc28.x86_64 libgcrypt-1.8.3-1.fc28.x86_64 libgpg-error-1.31-1.fc28.x86_64 libmount-2.32.1-1.fc28.x86_64 libpng-1.6.34-6.fc28.x86_64 libselinux-2.8-1.fc28.x86_64 libstdc++-8.2.1-5.fc28.x86_64 libthai-0.1.28-1.fc28.x86_64 libuuid-2.32.1-1.fc28.x86_64 libwayland-client-1.15.0-1.fc28.x86_64 libwayland-cursor-1.15.0-1.fc28.x86_64 libwayland-egl-1.15.0-1.fc28.x86_64 libxcb-1.13-1.fc28.x86_64 libxkbcommon-0.8.2-1.fc28.x86_64 lz4-libs-1.8.1.2-4.fc28.x86_64 pango-1.42.4-1.fc28.x86_64 pcre-8.42-5.fc28.x86_64 pcre2-10.32-4.fc28.x86_64 pixman-0.34.0-8.fc28.x86_64 systemd-libs-238-10.git438ac26.fc28.x86_64 xz-libs-5.2.4-2.fc28.x86_64 zlib-1.2.11-8.fc28.x86_64
(gdb) bt
#0  0x00007ffff40eeeab in raise () at /lib64/libc.so.6
#1  0x00007ffff40d95b9 in abort () at /lib64/libc.so.6
#2  0x00007ffff40d9491 in _nl_load_domain.cold.0 () at /lib64/libc.so.6
#3  0x00007ffff40e7612 in  () at /lib64/libc.so.6
#4  0x0000000000462a04 in xe::cpu::testing::TestFunction::Run(std::function<void (xe::cpu::ppc::PPCContext_s*)>, std::function<void (xe::cpu::ppc::PPCContext_s*)>) ()
#5  0x0000000000448d4f in ____C_A_T_C_H____T_E_S_T____0() ()
#6  0x0000000000503483 in Catch::FreeFunctionTestCase::invoke() const ()
#7  0x00000000004f575d in Catch::TestCase::invoke() const ()
#8  0x00000000005159dd in Catch::RunContext::invokeActiveTestCase() ()
#9  0x000000000051558a in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#10 0x00000000004fe091 in Catch::RunContext::runTest(Catch::TestCase const&) ()
#11 0x00000000004f2940 in Catch::runTests(Catch::Ptr<Catch::Config> const&) ()
#12 0x000000000052b3ec in Catch::Session::run() ()
#13 0x0000000000502180 in Catch::Session::run(int, char const* const*) ()
#14 0x00000000004fc12e in xe::Main(int, char**) ()
#15 0x00000000004fc202 in main ()

```

**Comment by DrChat** [comment]
It's possible that Xenia can't run JITted code in Linux due to some system constraints (execute pages cannot have write permissions set). Will have to investigate.

**Comment by rcaridade145** [comment]
More info on ".note.gnu.property" here http://lists.llvm.org/pipermail/llvm-dev/2018-March/121951.html And here on ld http://man7.org/linux/man-pages/man1/ld.1.html
