### ISSUE TITLE
xb.bat not work  UnicodeDecodeError: 'gbk' codec 

### ISSUE THREAD

**Issue by yxmline** [xenia-project/xenia#1479]
```
Active code page: 65001

D:\xxxx\xenia\build\xenia>xb.bat setup
Traceback (most recent call last):
  File "D:\xxxx\xenia\build\xenia\\xenia-build", line 1456, in <module>
    main()
  File "D:\xxxx\xenia\build\xenia\\xenia-build", line 47, in main
    vs_version = import_vs_environment()
  File "D:\xxxx\xenia\build\xenia\\xenia-build", line 99, in import_vs_environment
    vswhere = subprocess.check_output('third_party/vswhere/vswhere.exe -version "[15,)" -latest -prerelease -format json -utf8', shell=False, universal_newlines=True)
  File "C:\ProgramData\Anaconda3\x64\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\x64\lib\subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\ProgramData\Anaconda3\x64\lib\subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 734: illegal multibyte sequence
```
```
D:\xxxx\xenia\build\xenia>python xenia-build build
Traceback (most recent call last):
  File "xenia-build", line 1456, in <module>
    main()
  File "xenia-build", line 47, in main
    vs_version = import_vs_environment()
  File "xenia-build", line 99, in import_vs_environment
    vswhere = subprocess.check_output('third_party/vswhere/vswhere.exe -version "[15,)" -latest -prerelease -format json -utf8', shell=False, universal_newlines=True)
  File "C:\ProgramData\Anaconda3\x64\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\x64\lib\subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\ProgramData\Anaconda3\x64\lib\subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 734: illegal multibyte sequence
```

**Comment by Margen67** [comment]
@yxmline Do you have Visual Studio installed?

**Comment by yxmline** [comment]
Yes,Visual Studio 2015
